###Artistas---------

###Obtener todos los artistas
GET http://localhost:1234/artist/

###Obtener un artista por id
GET http://localhost:1234/artist/1

### Crear un artista
POST http://localhost:1234/artist/
Content-Type: application/json

{
  "Name": "Avenged Sevenfold"
}

### Actualizar un artista
PUT http://localhost:1234/artist/2
Content-Type: application/json

{
  "Name": "Naoki"
}

###Borrar un artista por Id
DELETE http://localhost:1234/artist/1
